export const CREATE_SECRET_REQUEST = "CREATE_SECRET_REQUEST";
export const CREATE_SECRET_SUCCESS = "CREATE_SECRET_SUCCESS";
export const CREATE_SECRET_FAIL = "CREATE_SECRET_FAIL";

export const GET_SECRET_REQUEST = "GET_SECRET_REQUEST";
export const GET_SECRET_SUCCESS = "GET_SECRET_SUCCESS";
export const GET_SECRET_FAIL = "GET_SECRET_FAIL";